[package]
name = "libsql-syncd"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.3"
libsql = "0.3.5"
log = "0.4.21"
redis = { version = "0.25.4", features = ["tokio-rustls-comp"] }
tokio = "1.37.0"
